#!/usr/bin/env node
// Run right after `ng new` (with --skip-install) and BEFORE scaffold.mjs.
// `ng new --ai-config=claude-code` writes CLAUDE.md + .mcp.json next to the Angular workspace. Those are
// the CLI-owned, version-matched Angular guidelines: keep their content but relocate it so it loads only
// when Claude touches web files (a path-scoped rule) and so MCP config sits at the project root.
//
//   node post-ng-new.mjs --out <projectRoot> --mode mono|single
//
// mono:   apps/web/{CLAUDE.md,.mcp.json,.prettierrc,.editorconfig,.gitignore,README.md,.vscode} -> hoisted/removed
// single: CLAUDE.md -> .claude/rules/web.md ; .prettierrc removed (prettier.config.mjs replaces it)

import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const a = process.argv.slice(2);
const opt = (n, d) => (a.includes(`--${n}`) ? a[a.indexOf(`--${n}`) + 1] : d);
const out = resolve(opt('out', '.'));
const mono = opt('mode', 'mono') === 'mono';
const web = mono ? join(out, 'apps', 'web') : out;
const done = [];

// 1. Angular guidelines -> path-scoped rule
const claude = join(web, 'CLAUDE.md');
if (existsSync(claude)) {
  const body = readFileSync(claude, 'utf8');
  const glob = mono ? 'apps/web/**' : 'src/**';
  mkdirSync(join(out, '.claude', 'rules'), { recursive: true });
  writeFileSync(join(out, '.claude', 'rules', 'web.md'), `---\npaths:\n  - "${glob}"\n---\n\n<!-- Generated by \`ng new --ai-config=claude-code\` (Angular CLI, matches the installed Angular version). Regenerate rather than hand-edit; project-specific web rules go in web-project.md -->\n\n${body}`);
  rmSync(claude);
  done.push('CLAUDE.md -> .claude/rules/web.md');
}

// 2. MCP config -> project root (merge, keep any existing servers)
const mcp = join(web, '.mcp.json');
if (existsSync(mcp)) {
  if (mono) {
    const rootMcp = join(out, '.mcp.json');
    const base = existsSync(rootMcp) ? JSON.parse(readFileSync(rootMcp, 'utf8')) : {};
    const add = JSON.parse(readFileSync(mcp, 'utf8'));
    base.mcpServers = { ...(base.mcpServers ?? {}), ...(add.mcpServers ?? {}) };
    writeFileSync(rootMcp, JSON.stringify(base, null, 2) + '\n');
    rmSync(mcp);
    done.push('.mcp.json hoisted to project root');
  }
}

// 3. Files the root provides itself
for (const f of mono ? ['.prettierrc', '.editorconfig', '.gitignore', 'README.md'] : ['.prettierrc']) {
  const p = join(web, f);
  if (existsSync(p)) {
    if (mono && f === '.editorconfig' && !existsSync(join(out, f))) renameSync(p, join(out, f));
    else rmSync(p);
    done.push(`${f} ${mono && f === '.editorconfig' ? 'hoisted' : 'removed'}`);
  }
}
if (mono) {
  // The root owns prettier (and its plugins); keep apps/web free of a duplicate devDependency.
  const pkgPath = join(web, 'package.json');
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  if (pkg.devDependencies?.prettier) {
    delete pkg.devDependencies.prettier;
    writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
    done.push('apps/web: prettier devDependency removed (root owns it)');
  }
}
console.log(JSON.stringify({ out, mode: mono ? 'mono' : 'single', done }, null, 2));
