# {{name}}

Angular web app{{#if mono}} with a Fastify API and DTOs shared through Zod schemas (pnpm monorepo){{/if}}. Written to be worked on by AI agents: small always-loaded context, details in path-scoped rules.

## Layout

{{#if mono}}
| Path | What |
|---|---|
| `apps/web` | Angular app (zoneless, signals, Angular Aria + Tailwind v4) |
| `apps/api` | Fastify API (Zod validation, Vitest + `app.inject()` tests) |
| `packages/shared` | **The only home of DTOs**: Zod schemas + inferred types, used by web, api and e2e |
| `e2e` | Playwright tests (+ axe accessibility checks) |
{{/if}}
{{#if single}}
| Path | What |
|---|---|
| `src/` | Angular app (zoneless, signals, Angular Aria + Tailwind v4) |
| `e2e/` | Playwright tests (+ axe accessibility checks) |
{{/if}}

## Commands

| Command | Use |
|---|---|
| `pnpm check` | **The quality gate** (format, lint, typecheck, unit tests, knip). One line per step on success, failure output only on failure. Run it before saying anything is done. |
| `pnpm check lint test` | Only some steps (`format lint typecheck test knip`). Add `-- --full` for untrimmed failure output. |
| `pnpm fix` | ESLint `--fix` + Prettier write. Run it instead of fixing style by hand. |
{{#if mono}}
| `pnpm test:api` | API tests only |
{{/if}}
| `pnpm test:e2e` | Playwright (starts the dev server{{#if mono}}s{{/if}} itself). Run it when behaviour visible to users changed. |
| `pnpm dev` | Dev server{{#if mono}}s (web on 4200, API on 3000, `/api` proxied){{/if}} |
| `pnpm build` | Production build |

## Definition of done

1. `pnpm check` is green. 2. Behaviour changes have tests (unit{{#if mono}}, API{{/if}}, and e2e for user-visible flows). 3. New routes get an axe test in `e2e/tests`. 4. No `eslint-disable` without a written reason; fix the code, not the rule.

## Conventions that always apply

- TypeScript is strict. No `any`, no non-null `!`; narrow or validate instead.
- ESLint is **error or off**, never warn. If a rule seems wrong, say so instead of disabling it.
- Angular 2025 style guide naming: `user-profile.ts` holds `class UserProfile` (no `.component`/`Component` suffix); `.model.ts` for plain types.
- UI: Angular Aria directives for interactive patterns (tabs, menu, listbox, accordion, …), Tailwind v4 utilities for styling, state variants via `aria-*:`/`data-*:`. No UI kit, no `tailwind.config.js`.
{{#if mono}}
- A DTO is a Zod schema in `packages/shared`; types come from `z.infer`. Never redefine a request/response shape in web or api.
{{/if}}
- Tests are colocated (`*.spec.ts`); e2e locators are roles/labels (`getByRole`), not CSS.

## Token hygiene

Use `pnpm check` rather than the individual tools. Do not read `dist/`, `coverage/`, `pnpm-lock.yaml` (denied in `.claude/settings.json`). Read issues with `gh issue view N --json title,body,labels`, CI failures with `gh run view <id> --log-failed`. For Angular API questions use the `angular-cli` MCP server (`get_best_practices`, `find_examples`, `search_documentation`) instead of fetching web pages.

## Working from an issue

1. `gh issue view <N> --json title,body,labels` (issues follow the forms in `.github/ISSUE_TEMPLATE`; the acceptance criteria are the spec).
2. Branch `feat/<N>-slug`, `fix/<N>-slug` or `chore/<N>-slug`.
3. Implement; add the tests the issue lists under "Tests required". Commit in Conventional Commits format.
4. `pnpm check` (+ `pnpm test:e2e` when needed) green.
5. Open a PR from the template with `Closes #<N>`; its title is a Conventional Commit (`fix(web): ...`).

## Commits and pull requests

[Conventional Commits](https://www.conventionalcommits.org): `type(scope): subject`, imperative, no trailing period.
Types: `feat` `fix` `docs` `style` `refactor` `perf` `test` `build` `ci` `chore` `revert`. Optional scope: {{#if mono}}`web` `api` `shared` {{/if}}{{#if single}}`web` {{/if}}`e2e` `ci` `deps` `docs`. Breaking change: `feat(api)!: ...` or a `BREAKING CHANGE:` footer.
A `commit-msg` hook (husky + commitlint) rejects anything else, and CI checks every commit and the **PR title**, which is
the squash-merge commit message: write it in the same format. Branch prefix follows the type (`feat/`, `fix/`, `chore/`).
If a hook is missing after cloning or `git init`, run `pnpm install` (the `prepare` script installs it). Never bypass it with `--no-verify`.

## Where the detail lives (read on demand, do not paste into context)

Path-scoped rules in `.claude/rules/` load automatically when you touch matching files (`web.md` is generated by the Angular CLI, `web-project.md` is ours{{#if mono}}, `api.md`, `shared-dtos.md`{{/if}}, `e2e.md`, `github.md`{{#if db}}, `db.md`{{/if}}{{#if auth}}, `auth.md`{{/if}}{{#if pwa}}, `pwa.md`{{/if}}{{#if notifs}}, `notifications.md`{{/if}}). Longer notes: `docs/ai/architecture.md` (why things are the way they are), `docs/ai/troubleshooting.md` (known pitfalls).

## Gotchas

{{#if mono}}
- TypeScript is **split on purpose**: root and `apps/web` use `~6.0` (Angular and typescript-eslint reject 7); `apps/api` and `packages/shared` use TypeScript 7 for fast typechecks. `packages/shared` is also checked with 6 at the root because Angular compiles it. Never run `pnpm add typescript@latest`.
{{/if}}
{{#if single}}
- TypeScript is pinned to `~6.0`: Angular and typescript-eslint reject 7. Never run `pnpm add typescript@latest`.
{{/if}}
- `strictPeerDependencies` is on: a peer conflict fails the install. Resolve it, do not use `--legacy-peer-deps`.
- Generated Angular files are formatted/linted by the same gate: after `ng generate`, run `pnpm fix`.
